# Generated by Django 5.2 on 2025-04-28 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('no_localunits', models.IntegerField()),
                ('no_metropolitan', models.IntegerField()),
                ('no_municipalities', models.IntegerField()),
                ('no_villageCouncil', models.IntegerField()),
                ('total_population', models.IntegerField()),
                ('male_population', models.IntegerField()),
                ('female_population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('party_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('party_shortname', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='logo/')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('province_headquarter', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Local_unit',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('no_wards', models.IntegerField()),
                ('no_electionCenter', models.IntegerField()),
                ('total_population', models.IntegerField()),
                ('no_maleVoters', models.IntegerField()),
                ('no_femaleVoters', models.IntegerField()),
                ('no_otherVoters', models.IntegerField()),
                ('total_eligibleVoters', models.IntegerField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.district')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='candidate_photo/')),
                ('position', models.CharField(max_length=100)),
                ('vote', models.IntegerField()),
                ('ward', models.IntegerField()),
                ('local_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.local_unit')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.party')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.province'),
        ),
    ]
