# Generated by Django 5.2 on 2025-05-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='votes',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(upload_to='images/candidate_photo/'),
        ),
        migrations.AlterField(
            model_name='party',
            name='logo',
            field=models.ImageField(upload_to='images/logo/'),
        ),
    ]
