# Generated by Django 5.2 on 2025-04-27 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vote', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100, unique=True)),
                ('district_headquarter', models.CharField(max_length=100)),
                ('district_population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Election_position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Local_unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.district')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=100)),
                ('party_shortname', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('party_totalvote', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=100, unique=True)),
                ('province_headquarter', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_number', models.IntegerField(unique=True)),
                ('ward_population', models.IntegerField()),
                ('local_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.local_unit')),
            ],
        ),
        migrations.DeleteModel(
            name='Parties',
        ),
        migrations.AddField(
            model_name='candidate',
            name='election_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.election_position'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='local_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.local_unit'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.party'),
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.province'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.ward'),
        ),
    ]
