# Generated by Django 5.2 on 2025-04-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_candidate_district_election_position_local_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='id',
        ),
        migrations.RemoveField(
            model_name='election_position',
            name='id',
        ),
        migrations.RemoveField(
            model_name='local_unit',
            name='id',
        ),
        migrations.RemoveField(
            model_name='party',
            name='id',
        ),
        migrations.RemoveField(
            model_name='province',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='id',
        ),
        migrations.AlterField(
            model_name='district',
            name='district_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='election_position',
            name='post',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='local_unit',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='province',
            name='province_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ward',
            name='ward_number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
