# Generated by Django 5.2 on 2025-05-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_party_votes_alter_candidate_photo_alter_party_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='chairmen',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
