# Generated by Django 5.2 on 2025-05-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_party_chairmen'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='Is_elected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='education_level',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.CharField(choices=[('Mayor', 'Mayor'), ('Deputy Mayor', 'Deputy Mayor'), ('Chairperson', 'Chairperson'), ('Vice Chairperson', 'Vice Chairperson'), ('Ward President', 'Ward President'), ('Female Member', 'Female Member'), ('Dalit Female Member', 'Dalit Female Member'), ('Member', 'Member')], max_length=100),
        ),
    ]
